# Excluded files
exclude: README.md

# Site info
url: "https://uncertaintysedge.github.io"
title: "Uncertainty's Edge"
name: "Uncertainty's Edge"
description: "Everything is complicated"
markdown: kramdown

# Style
theme: jekyll-theme-tactile

# Defaults
defaults:
  -
  scope:
  path: "" # an empty string here means all files in the project
  values:
  layout: "default"
  author: "Uncertainty's Edge"